- name: "[Base] Install aptitude using apt"
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes
  tags: docker

- name: "[Base] Install required system packages"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  tags: docker
  loop:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
    - "python3-pip"
    - "virtualenv"
    - "python3-setuptools"
    - "python3-distutils"

- name: "[Flatpak] Install required system packages for Flatpak"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  tags: sequeler, flatpak
  loop:
    - "gnome-software"
    - "gnome-software-plugin-flatpak"

- name: "[Base] Install basic tools"
  apt:
    name: "{{ item }}"
    state: latest
  tags: base
  loop: "{{ apt_packages }}"

- name: "[pip] Install pip packages --user"
  become: no
  pip:
    name: "{{ item }}"
    extra_args: --user
  tags: pip
  loop: "{{ pip_user_packages }}"

- import_tasks: dev/git.yml
  become: no
  tags: git, dev, lotion

- import_tasks: dev/docker.yml
  tags: docker, dev

- import_tasks: dev/vscodium.yml
  tags: codium, dev

- import_tasks: dev/mysqlcli.yml
  tags: mysql, dev, db

- import_tasks: tools/lotion.yml
  become: no
  tags: lotion, binaries, tools

- import_tasks: dev/sequeler.yml
  tags: sequeler, dev, db

- import_tasks: dev/dbeaver.yml
  tags: dbeaver, binaries, dev, db

- import_tasks: dev/node.yml
  become: no
  tags: node, nvm, npm, binaries, dev

- import_tasks: dev/circleci.yml
  tags: circleci, binaries, dev

- import_tasks: tools/slack.yml
  tags: slack, binaries, tools

- import_tasks: tools/zoom.yml
  tags: zoom, binaries, tools
- import_tasks: dev/terraform.yml
  tags: terraform, binaries, dev

- import_tasks: dev/kubectl.yml
  tags: kubernetes, binaries, dev

- import_tasks: dev/aws-iam-authenticator.yml
  tags: kubernetes, binaries, dev

- import_tasks: dev/shellcheck.yml
  tags: shellcheck, binaries, dev

- import_tasks: tools/tilda.yml
  tags: tilda, binaries, tools

- import_tasks: tools/wtfutil.yml
  tags: wtfutil, binaries, tools

- import_tasks: tools/moodo.yml
  tags: moodo, binaries, tools

- import_tasks: tools/gtweaks.yml
  tags: gnome, tweaks, binaries, tools

- name: "[Snap] Install snaps"
  snap:
    name: "{{ item }}"
  loop: "{{ snap_packages }}"
  tags: snap
