- name: "[DBeaver] Download dbeaver"
  get_url:
    url: "https://dbeaver.io/files/dbeaver-ce_latest_{{ linux_arch }}.deb"
    dest: /tmp/dbeaver.deb

- name: "[DBeaver] Install dbeaver"
  apt:
    deb: /tmp/dbeaver.deb
