- name: "[docker] Add Docker GPG apt Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "[docker] Add Docker Repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "[docker] Update apt and install docker-ce"
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: "[docker] Install docker-compose"
  become: no
  pip:
    name: docker-compose
    extra_args: --user

- name: "[docker] Get docker-compose to be run as root"
  shell: "usermod -a -G docker '{{ user }}'"
