- name: "[git] Add Git Repository"
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: "[git] Update apt and install git"
  apt:
    name: git
    state: latest
    
- name: "[git] Setup email on git config"
  become: no
  git_config:
    scope: global
    name: user.email
    value: "{{ email }}"

- name: "[git] Setup name on git config"
  become: no
  git_config:
    scope: global
    name: user.name
    value: "{{ name }}"
