- name: Add Git Repository
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Update apt and install git
  apt:
    name: git
    state: latest

- name: Install git-crypt
  apt:
    name: git-crypt
    state: latest

- name: Setup email on git config
  become: no
  git_config:
    scope: global
    name: user.email
    value: "{{ email }}"

- name: Setup name on git config
  become: no
  git_config:
    scope: global
    name: user.name
    value: "{{ name }}"
