- name: "[codium] Add VSCodium GPG apt Key"
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: "[codium] Add VSCodium Repository"
  apt_repository:
    repo: deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main
    state: present

- name: "[codium] Update apt and install VSCodium"
  apt:
    name: codium
    state: latest
    update_cache: yes
